### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Ekta#1]
Please go to https://github.com/EbenSorkin/Ekta/settings and rename the repo to Asar

**Comment by EbenSorkin** [comment]
I tried to sort out how that was done earlier. I don’t see a way to get it done either in the Git app I have or the Git website.

I thought about creating a new archive with the correct name but I wasn’t sure if that would cause a problem. If not then I can do that quickly now.

What makes best sense?

-e.

**Comment by davelab6** [comment]
Go that that URL and at the top you can just rename it :) You see 'Ekta' in
an input box, you change it

On 11 May 2015 at 18:49, Eben Sorkin notifications@github.com wrote:

> I tried to sort out how that was done earlier. I don’t see a way to get it
> done either in the Git app I have or the Git website.
> 
> I thought about creating a new archive with the correct name but I wasn’t
> sure if that would cause a problem. If not then I can do that quickly now.
> 
> What makes best sense?
> 
> -e.
> 
> On May 11, 2015, at 8:43 AM, Dave Crossland notifications@github.com
> wrote:
> 
> > Please go to https://github.com/EbenSorkin/Ekta/settings and rename the
> > repo to Asar
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EbenSorkin/Ekta/issues/1#issuecomment-100995922.

## 

Cheers
Dave

**Comment by EbenSorkin** [comment]
I finally found it in Settings. Done.

**Comment by davelab6** [comment]
:8ball:
